sudo: required
dist: trusty
before_install:
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german  texlive-science texlive-math-extra texlive-font-utils latex-xcolor

script:
- cd Tex
- pdflatex -interaction=nonstopmode -halt-on-error main.tex
- bibtex main
- pdflatex -interaction=nonstopmode -halt-on-error main.tex
- pdflatex -interaction=nonstopmode -halt-on-error main.tex
deploy:
  provider: releases
  api_key:
    secure: T89M0704TLSCtQVF1dczBXn0z9vWZn7oBHmLlFjvXoEUzZ/FPwIdQVrwPKHeFCZeqB0oq4m5dzKn7xONAx0Xbn08S/yBqW8a0iD2SZwZAQZbQT0o8Dw63daXNtcuJiRiK4f7GFXkkgPqYBeYevAy5rj2hfu1V2TDrvtd3BG9XDtsQMIiiNjwrnt/ejFgEV1bCpuwVJKH3eeCtR8iqMrclxfKStkXW6ZWiD3zMvGPGQ8vRZAw80i05Tmexi5oAJAw2D+iaJYpk5YdgDon3YswJJW2RPW6gSoHkIUA+V/pqbTk2OQYQXfgl5ZkGssC71ecKgF+gnOfkGIRbQ/yLtZ9O70xfQrFCD4PtxnWy/GxGmNOdP7rK0MkDZIxfXATF7X5CH/L5sV6DsnVnbY7WCNnYPuYTk2UroA9QQmAs9hBnLOyBLxDwDxXDvJh7k8GjVWfgUPS1M375/36zphQqsEt/Kv60/S9CcgyqA1k2TEl/johVebsm4D0CIZvfE0Jbps+OT7eV3FDWd77UU49cLE0BFX1uLynPQVtvN/F4F8x2yeD9jfJcV3dzNN1b5vaoLfy5TmAcapSBDCzaYx9Q91nst4HT8eIHWo5XVX9l5G80c+KFat8usjIqy4hOS8MuGAYAJE6XL/ACYy3RwQaTTtTnC3mzA2Flkx+9jaMFQsNRwg=
  file: main.pdf
  on:
    repo: fzimmermann89/bsc
tags: true
